### ISSUE TITLE
ex4_2_cnn_cifar10_cl 실행하니 you forgot to call super(YourClass, self).__init__() 에러가 납니다.

### ISSUE THREAD

**Issue by softgearko** [jskDr/keraspp#3]
ex4_2_cnn_cifar10_cl 실행하니 아래와 같은 에러가 납니다.
도와주세요.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/softg/PycharmProjects/test/keraspp/ex4_2_cnn_cifar10_cl.py", line 22, in <module>
    main()
  File "C:/Users/softg/PycharmProjects/test/keraspp/ex4_2_cnn_cifar10_cl.py", line 18, in main
    m = Machine()
  File "C:/Users/softg/PycharmProjects/test/keraspp/ex4_2_cnn_cifar10_cl.py", line 14, in __init__
    super().__init__(X, y, nb_classes=10)
  File "C:\Users\softg\PycharmProjects\test\keraspp\keraspp\aicnn.py", line 125, in __init__
    self.set_model()
  File "C:\Users\softg\PycharmProjects\test\keraspp\keraspp\aicnn.py", line 136, in set_model
    self.model = CNN(nb_classes=nb_classes, in_shape=data.input_shape)
  File "C:\Users\softg\PycharmProjects\test\keraspp\keraspp\aicnn.py", line 25, in __init__
    model.build_model()
  File "C:\Users\softg\PycharmProjects\test\keraspp\keraspp\aicnn.py", line 49, in build_model
    model.cl_part = Model(x, z_cl)
  File "C:\Users\softg\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 316, in __setattr__
    'It looks like you are subclassing `Model` and you '
RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super(YourClass, self).__init__()`. Always start with this line.

Process finished with exit code 1
```

**Comment by kim-taehee** [comment]
같은 에러가 발생합니다

**Comment by dnr3663** [comment]
class CNN(Model):
    def __init__(model, nb_classes, in_shape=None):
        super().__init__()           <<-- 추가하여 해결하였습니다.
        model.nb_classes = nb_classes
        model.in_shape = in_shape
        model.build_model()
        super().__init__(model.x, model.y)
        model.compile()

**Comment by yong6600** [comment]
keras version 을 2.2.2에서 2.1.3으로 다운그레이딩 하여 해결 하였습니다

**Comment by saekomdalkom** [comment]
이 코드에 에러가 너무 많아서 고치느라 고생했네요 ㅠㅠ
```
# aicnn.py에서 
from . import skeras
from . import sfile
```
를
```
import keraspp.skeras as skeras
import keraspp.sfile as sfile
```
이렇게 고쳤고, 
class CNN(Model) 안에서 사용되는 model 변수(상속받은 keras의 대문자 Model아님 주의)를 전부 self로 바꿔줬더니 정상적으로 돌아갑니다.
